<%
'ErrMsg("ddd")
Sub ErrMsg(ByVal ErrText)
	With Response
		.Clear()
		.AddHeader "X-Robots-Tag", "noindex, nofollow, noarchive, noimageindex"
		.Write("<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">" & vbCrLf)
		.Write("<!--[if IE 6]><html class=""ie6"" xmlns=""http://www.w3.org/1999/xhtml"" lang=""tr_TR""><![endif]-->" & vbCrLf)
		.Write("<!--[if IE 7]><html class=""ie7"" xmlns=""http://www.w3.org/1999/xhtml"" lang=""tr_TR""><![endif]-->" & vbCrLf)
		.Write("<!--[if !(IE)]><html xmlns=""http://www.w3.org/1999/xhtml"" lang=""tr_TR""><![endif]-->" & vbCrLf)
		.Write("	<head>" & vbCrLf)
		.Write("		<meta http-equiv=""Content-Type"" content=""text/html; charset=UTF-8"" />" & vbCrLf)
		.Write("		<meta name=""author"" content=""Ferdi Tarakcı, www.webtasarimx.net"" />" & vbCrLf)
		.Write("		<meta name=""generator"" content=""webtasarimx.net - Freelance Web Developer"" />" & vbCrLf)
		.Write("		<meta name=""reply-to"" content=""ferdi@webtasarimx.net"" />" & vbCrLf)
		.Write("		<meta name=""robots"" content=""noindex, nofollow, noarchive, noimageindex"" />" & vbCrLf)
		.Write("		<title>Hata Oluştu! - webtasarimx.net</title>" & vbCrLf)
		.Write("		<link href=""http://www.webtasarimx.net/favicon.ico"" rel=""shortcut icon"" type=""image/x-icon"" title=""Web Tasarım"" />" & vbCrLf)
		.Write("		<style type=""text/css"">" & vbCrLf)
		.Write("			/*" & vbCrLf)
		.Write("				Copyright © 2008 - "& Year(Date) &"" & vbCrLf)
		.Write("				Freelance Web Developer - Ferdi Tarakcı" & vbCrLf)
		.Write("				www.webtasarimx.net" & vbCrLf)
		.Write("				ferdi@webtasarimx.net" & vbCrLf)
		.Write("			*/" & vbCrLf)
		.Write("			* {" & vbCrLf)
		.Write("				margin:0; " & vbCrLf)
		.Write("				padding:0;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			html {" & vbCrLf)
		.Write("				overflow:auto;" & vbCrLf)
		.Write("				overflow-y:scroll;" & vbCrLf)
		.Write("				min-height:100%;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			html.ie7 body {" & vbCrLf)
		.Write("				overflow:hidden;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			body {" & vbCrLf)
		.Write("				font-family:""Segoe UI"", Arial;" & vbCrLf)
		.Write("				line-height:1;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error {" & vbCrLf)
		.Write("				margin: 2em auto;" & vbCrLf)
		.Write("				padding: 1em 2em;" & vbCrLf)
		.Write("				color:#fff;" & vbCrLf)
		.Write("				font:85%;" & vbCrLf)
		.Write("				background-color:#f5f5f5;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error-content {" & vbCrLf)
		.Write("				width: 600px;" & vbCrLf)
		.Write("				margin: 1.5em auto;" & vbCrLf)
		.Write("				padding: 25px 10px;" & vbCrLf)
		.Write("				text-align: center;" & vbCrLf)
		.Write("				border: 1px solid #dfdfdf;" & vbCrLf)
		.Write("				background-color: #fff;" & vbCrLf)
		.Write("				border-radius: 8px;" & vbCrLf)
		.Write("				-moz-border-radius: 8px;" & vbCrLf)
		.Write("				-khtml-border-radius: 8px;" & vbCrLf)
		.Write("				-webkit-border-radius: 8px;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error-content h1 {" & vbCrLf)
		.Write("				margin:0;" & vbCrLf)
		.Write("				padding:0 0 5px 0;" & vbCrLf)
		.Write("				line-height:18px;" & vbCrLf)
		.Write("				font-size: 17px;" & vbCrLf)
		.Write("				color:#444;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error-content h2 {" & vbCrLf)
		.Write("				margin:0;" & vbCrLf)
		.Write("				padding:0 0 5px 0;" & vbCrLf)
		.Write("				line-height:14px;" & vbCrLf)
		.Write("				font-size: 13px;" & vbCrLf)
		.Write("				color:#444;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error-content p {" & vbCrLf)
		.Write("				margin:0;" & vbCrLf)
		.Write("				margin-bottom:5px;" & vbCrLf)
		.Write("				padding:0;" & vbCrLf)
		.Write("				line-height:15px;" & vbCrLf)
		.Write("				font-size: 14px;" & vbCrLf)
		.Write("				color:#444;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error-content span {" & vbCrLf)
		.Write("				color:#f00;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			#ewy-error-content .line {" & vbCrLf)
		.Write("				margin-bottom:6px;" & vbCrLf)
		.Write("				padding:3px 0;" & vbCrLf)
		.Write("				border-bottom:1px solid #ccc;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.clearfix:after {" & vbCrLf)
		.Write("				content:""."";" & vbCrLf)
		.Write("				clear:both;" & vbCrLf)
		.Write("				display:block;" & vbCrLf)
		.Write("				visibility:hidden;" & vbCrLf)
		.Write("				height:0;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.clearfix {" & vbCrLf)
		.Write("				display:inline-block;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			* html .clearfix { /* Hides From IE-MAC \*/" & vbCrLf)
		.Write("				height:1%;" & vbCrLf)
		.Write("				display:inline-block;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.clearfix { /* Endhide From IE-MAC \*/" & vbCrLf)
		.Write("				display:block;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.ie6 .clearfix {" & vbCrLf)
		.Write("				height:1%;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.ie6 .clearfix, .ie7 .clearfix, .ie8 .clearfix {" & vbCrLf)
		.Write("				zoom:1;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.clr {" & vbCrLf)
		.Write("				clear:both;" & vbCrLf)
		.Write("				display:block;" & vbCrLf)
		.Write("				font-size:0;" & vbCrLf)
		.Write("				line-height:0;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("			.hidden {" & vbCrLf)
		.Write("				display:none;" & vbCrLf)
		.Write("			}" & vbCrLf)
		.Write("		</style>" & vbCrLf)
		.Write("	</head>" & vbCrLf)
		.Write("	<body id=""ewy-error"">" & vbCrLf)
		.Write("		<div id=""ewy-error-content"">" & vbCrLf)
		.Write("			<h1>Web Developer: Ferdi TARAKCI</h1>" & vbCrLf)
		.Write("			<h2>Web Site: www.webtasarimx.net</h2>" & vbCrLf)
		.Write("			<h2>Mail: ferdi@webtasarimx.net</h2>" & vbCrLf)
		.Write("			<div class=""line""></div>" & vbCrLf)
		.Write("			<p><span>" & ErrText & "</span></p>" & vbCrLf)
		.Write("		</div>" & vbCrLf)
		.Write("	</body>" & vbCrLf)
		.Write("</html>")
		'// .Status = "404 Not Found"
	End With
	If Not inStr(1, LCase(Request.ServerVariables("QUERY_STRiNG")), GlobalConfig("admin_folder"), 1) > 0 Or Session("admin_username") = "admin" Then Response.End()
End Sub
%>
